wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.9919311169115457
max_depth:
  desc: null
  value: 40
min_child_weight:
  desc: null
  value: 0.02612336742206688
n_estimators:
  desc: null
  value: 4955
num_leaves:
  desc: null
  value: 416
reg_alpha:
  desc: null
  value: 1.1202730271533006
reg_lambda:
  desc: null
  value: 1.092545441091484
subsample:
  desc: null
  value: 0.6876279010747738
