name: colorml
channels:
  - anaconda
  - defaults
dependencies:
  - black=19.10b0
  - click=7.0
  - pandas=1.0.1
  - python=3.7.6
  - scikit-learn=0.22
  - scipy=1.4.1
  - pip:
      - comet-ml==3.1.2
      - keras==2.3.1
      - probflow==2.0.0a2
      - ruamel-yaml==0.16.10
      - tensorboard==2.1.1
      - tensorflow==2.1.0
      - tensorflow-addons==0.8.3
      - tensorflow-estimator==2.1.0
      - tensorflow-probability==0.9.0
      - seaborn==0.10
      - webcolors==1.11
      - sqlalchemy==1.3
      - psycopg2==2.8.4
      - colour-science==0.3.15
      - xgboost==1.0.2
      - dill==0.3
