wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.4158962812443575
max_depth:
  desc: null
  value: 14
min_child_weight:
  desc: null
  value: 0.07216958672671728
n_estimators:
  desc: null
  value: 4514
num_leaves:
  desc: null
  value: 71
reg_alpha:
  desc: null
  value: 1.154073413895504
reg_lambda:
  desc: null
  value: 1.0967513776708897
subsample:
  desc: null
  value: 0.7952490415917923
