wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.8369246938705621
max_depth:
  desc: null
  value: 46
min_child_weight:
  desc: null
  value: 0.08629080919382277
n_estimators:
  desc: null
  value: 1444
num_leaves:
  desc: null
  value: 136
reg_alpha:
  desc: null
  value: 1.1879124996900718
reg_lambda:
  desc: null
  value: 1.1164574515666368
subsample:
  desc: null
  value: 0.25613080052779036
