wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.7105272216350192
max_depth:
  desc: null
  value: 10
min_child_weight:
  desc: null
  value: 0.026279526330821038
n_estimators:
  desc: null
  value: 2149
num_leaves:
  desc: null
  value: 379
reg_alpha:
  desc: null
  value: 1.2048251917854065
reg_lambda:
  desc: null
  value: 1.196513852838588
subsample:
  desc: null
  value: 0.1264360275514014
