wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.7004310096524453
max_depth:
  desc: null
  value: 36
min_child_weight:
  desc: null
  value: 0.04688928920796374
n_estimators:
  desc: null
  value: 2594
num_leaves:
  desc: null
  value: 191
reg_alpha:
  desc: null
  value: 1.0908231685715406
reg_lambda:
  desc: null
  value: 1.0221183805868521
subsample:
  desc: null
  value: 0.2559461997210065
