wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.8088779681072034
max_depth:
  desc: null
  value: 16
min_child_weight:
  desc: null
  value: 0.06783903991334245
n_estimators:
  desc: null
  value: 2417
num_leaves:
  desc: null
  value: 238
reg_alpha:
  desc: null
  value: 1.118574358746316
reg_lambda:
  desc: null
  value: 1.1203096134245016
subsample:
  desc: null
  value: 0.20958401272264954
