wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.39611825735788175
max_depth:
  desc: null
  value: 26
min_child_weight:
  desc: null
  value: 0.06150943247736757
n_estimators:
  desc: null
  value: 4545
num_leaves:
  desc: null
  value: 366
reg_alpha:
  desc: null
  value: 1.0652588297530332
reg_lambda:
  desc: null
  value: 1.1564051401192954
subsample:
  desc: null
  value: 0.549913598928214
