wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.6750561821992728
max_depth:
  desc: null
  value: 14
min_child_weight:
  desc: null
  value: 0.09717983774438509
n_estimators:
  desc: null
  value: 3814
num_leaves:
  desc: null
  value: 218
reg_alpha:
  desc: null
  value: 1.0347959834575424
reg_lambda:
  desc: null
  value: 1.1752565633701106
subsample:
  desc: null
  value: 0.43153316531974806
