wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.39100183479483264
max_depth:
  desc: null
  value: 8
min_child_weight:
  desc: null
  value: 0.001227582710772037
n_estimators:
  desc: null
  value: 4849
num_leaves:
  desc: null
  value: 50
reg_alpha:
  desc: null
  value: 1.0991594915967218
reg_lambda:
  desc: null
  value: 1.176121665990661
subsample:
  desc: null
  value: 0.4292849846098866
