wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.6154572707326313
max_depth:
  desc: null
  value: 18
min_child_weight:
  desc: null
  value: 0.03271183214338771
n_estimators:
  desc: null
  value: 3337
num_leaves:
  desc: null
  value: 201
reg_alpha:
  desc: null
  value: 1.0103324074315163
reg_lambda:
  desc: null
  value: 1.0054335221942865
subsample:
  desc: null
  value: 0.34574960977320834
