wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.7201332291412305
max_depth:
  desc: null
  value: 48
min_child_weight:
  desc: null
  value: 0.0014981303809375186
n_estimators:
  desc: null
  value: 3310
num_leaves:
  desc: null
  value: 118
reg_alpha:
  desc: null
  value: 1.0996056876474405
reg_lambda:
  desc: null
  value: 1.1046268079581492
subsample:
  desc: null
  value: 0.1690369781811645
