wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.10200040872763005
max_depth:
  desc: null
  value: 5
min_child_weight:
  desc: null
  value: 0.07063988761074537
n_estimators:
  desc: null
  value: 2868
num_leaves:
  desc: null
  value: 421
reg_alpha:
  desc: null
  value: 1.039441337422643
reg_lambda:
  desc: null
  value: 1.036352607621784
subsample:
  desc: null
  value: 0.269415437411504
