wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.17534789501614673
max_depth:
  desc: null
  value: 27
min_child_weight:
  desc: null
  value: 0.07888036371930819
n_estimators:
  desc: null
  value: 2702
num_leaves:
  desc: null
  value: 103
reg_alpha:
  desc: null
  value: 1.2109384653729613
reg_lambda:
  desc: null
  value: 1.0548254177634744
subsample:
  desc: null
  value: 0.39775412877277194
