wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.8138957048096771
max_depth:
  desc: null
  value: 38
min_child_weight:
  desc: null
  value: 0.032241458594238846
n_estimators:
  desc: null
  value: 2747
num_leaves:
  desc: null
  value: 58
reg_alpha:
  desc: null
  value: 1.0533228841521973
reg_lambda:
  desc: null
  value: 1.1801836789307962
subsample:
  desc: null
  value: 0.9528732590447992
