wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.4462130884782497
max_depth:
  desc: null
  value: 5
min_child_weight:
  desc: null
  value: 0.06543887304652837
n_estimators:
  desc: null
  value: 4163
num_leaves:
  desc: null
  value: 132
reg_alpha:
  desc: null
  value: 1.1721020332129162
reg_lambda:
  desc: null
  value: 1.1934651411871746
subsample:
  desc: null
  value: 0.49526719917428375
