wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.19191106845293054
max_depth:
  desc: null
  value: 24
min_child_weight:
  desc: null
  value: 0.046905579248507585
n_estimators:
  desc: null
  value: 4141
num_leaves:
  desc: null
  value: 11
reg_alpha:
  desc: null
  value: 1.1339581216450088
reg_lambda:
  desc: null
  value: 1.0597641478486213
subsample:
  desc: null
  value: 0.33362676922578605
