wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
colsample_bytree:
  desc: null
  value: 0.4129318880613757
max_depth:
  desc: null
  value: 44
min_child_weight:
  desc: null
  value: 0.07885445936239224
n_estimators:
  desc: null
  value: 3467
num_leaves:
  desc: null
  value: 409
reg_alpha:
  desc: null
  value: 1.1531943901840924
reg_lambda:
  desc: null
  value: 1.032440058637772
subsample:
  desc: null
  value: 0.7256889137759053
